name: Notify Discord with Mention

on:
  pull_request:
    types:
      - labeled

jobs:
  notify_discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Notify Discord
        if: |
          (
            (github.event.action == 'labeled' && github.event.label.name == 'test')
            ||
            (github.event.action == 'synchronize' && contains(github.event.pull_request.labels.*.name, 'test'))
          )
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_AS_BOT }}
          DISCORD_MENTION: "@everyone"  # メンションを追加
        run: |
          label_name="${{ github.event.label.name }}"
          pr_url="${{ github.event.pull_request.html_url }}"
          message="ラベルの種類: $label_name\nPR: $pr_url $DISCORD_MENTION"  # メンションをメッセージに追加
          curl -X POST -H "Content-Type: application/json" -d "$message" "$DISCORD_WEBHOOK_URL"
