name: Notify Discord with Mention

on:
  pull_request:
    types:
      - labeled

jobs:
  notify_discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Notify Discord
        if: |
          (
            (github.event.action == 'labeled' && github.event.label.name == '緊急')
            ||
            (github.event.action == 'synchronize' && contains(github.event.pull_request.labels.*.name, '緊急'))
          )
        env:
          PR_URL: "${{ github.event.pull_request.html_url }}"
        uses: appleboy/discord-action@0.0.3
        with:
          webhook_id: ${{ secrets.DISCORD_ID }}
          webhook_token: ${{ secrets.DISCORD_TOKEN }}
          color: "#48f442"
          username: "GitHub Bot"
          status: ${{ job.status }}
